### ISSUE TITLE
No python-layer notification of a failure in `_psfex_pywrap.PSFEx``

### ISSUE THREAD

**Issue by rmjarvis** [esheldon/psfex#4]
It is possible for `_psfex_pywrap.PSFEx` to return `None` rather than a valid `PSFEx` object.  In this case, later calls to `get_rec`, etc. give somewhat non-obvious AttributeErrors. 

 It would be nice if the `PSFEx.__init__` method could check if the constructor failed with `if self._psfex is None:` and raising a more descriptive exception about what the problem was, or at least that there was a problem.

**Comment by esheldon** [comment]
this is a bug, it should be raising an exception, probably IOError

**Comment by esheldon** [comment]
closed via be1acdcd56f7351dab06b80edd8117c1e2c68122

I used a ValueError
